apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i61om7zrb-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:33f7b7abc5e3844749c26c84dc7e60b55f3eca85@sha256:28121e67b60de7339dd7c785372249b3bbf373bd7d31a5f87d3c88e97b0069cb
          name: container-image
